Application_UI=https://practice.expandtesting.com/notes/app
Application_API=https://practice.expandtesting.com/notes/api/api-docs/
Browser=Chrome
Automation_Framework=Selenium Java + TestNG
API_Framework=RestAssured
Build_Tool=Maven
Reporting=Allure Reports
Parallel_Execution=Enabled
Environment=QA