# UI link
ui.base.url=https://practice.expandtesting.com/notes/app/login
# API site link
api.base.url=https://practice.expandtesting.com/notes/api
# Browser
browser=chrome
# Timeouts
implicit.wait=10
explicit.wait=20
# Credentials
valid.email=aan@gmail.com
valid.password=1234567
# Test data
invalid.note.id=000000000000000000000000